spring:
  application:
    name: backend

  profiles:
    active: local # 기본 프로파일

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
# 로컬 프로파일 (h2 인메모리)
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:moneylog;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
---
# 운영 프로파일 (Mysql 8)
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/moneylog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false